### ISSUE TITLE
WD移动硬盘无法挂载

### ISSUE THREAD

**Issue by lyzMaster** [ntfstool/ntfstool#11]
未开启ntfstool，插入WD移动硬盘后，MAC默认以只读模式打开硬盘。此时开启ntfstool，在ntfstool界面双击挂载移动硬盘，可是双击后移动硬盘不但无法挂载，且挂载失败后连只读的盘符都没有了

**Comment by ntfstool** [comment]
You can submit feedback in the program, and our technicians will analyze and try to fix this problem.

**Comment by changebaby1981** [comment]
The same thing happened

**Comment by ntfstool** [comment]
The reason is: due to the rapid shutdown of windows10, cache caching, forced loading will damage the data, so linux directly denied access.

The solutions are:-Re-enter windows and shut down normally. Just enter centos. However, this problem occurs again every time Windows quickly shuts down-restart into Windows, and turn off the Quick Start function in Control Panel-Power Options

As of NTFSTool2.2.0, there is no function to repair the cache forcibly mounting, you can try the above methods to solve it.

**Comment by dryqiao** [comment]
same problem, how to fix?
