### ISSUE TITLE
Unsupported macOS Version?

### ISSUE THREAD

**Issue by lirubao** [ntfstool/ntfstool#12]
My MacOS version 10.15.4,  The current ntfstool version(2.2.0) does not appear to be supported!

**Comment by ntfstool** [comment]
At present, there are many users of MacOS version 10.15.4 in normal use.I don't know whether it is the problem that the software cannot be opened, or the problem that the software cannot be mounted after it is opened?

**Comment by me-zss** [comment]
The problem is that the software cannot be mounted after it is opened.

**Comment by ntfstool** [comment]
You can click on the feedback in the software, we will collect the problem data and try to fix it. Thank you for your use.

**Comment by Abelisme** [comment]
hi my version is 10.15.2 and the current ntfstool version is 2.2.0, when i plug in my ntfs drive then open ntfstool, it will unmount my ntfs drive !!

**Comment by ntfstool** [comment]
The latest version V2.3.0 has been updated, and you can experience whether the problem is solved.If it is still not resolved, please contact the official technical service.

**Comment by fm365** [comment]
> hi my version is 10.15.2 and the current ntfstool version is 2.2.0, when i plug in my ntfs drive then open ntfstool, it will unmount my ntfs drive !!

I encountered the same problem.

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
