### ISSUE TITLE
macos10.15.4 ntfstool2.2.0 bootcamp无限挂载、死机

### ISSUE THREAD

**Issue by liemlian** [ntfstool/ntfstool#14]
macos10.15.4系统、ntfstool2.2.0版本、bootcamp无限挂载、死机。一旦启动这个软件，bootcamp就自动挂载，然后马上被卸载，再重新挂载，无限循环，导致电脑卡死。麻烦查一下原因，谢谢。

**Comment by ntfstool** [comment]
The reason is: due to the rapid shutdown of windows10, cache caching, forced loading will damage the data, so linux directly denied access.

The solutions:Re-enter windows and shut down normally. 
However, this problem occurs again every time Windows quickly shuts down-restart into Windows, and turn off the Quick Start function in Control Panel-Power Options

As of NTFSTool2.2.0, there is no function to repair the cache forcibly mounting, you can try the above methods to solve it.

We will add the function of automatic detection and repair in subsequent versions.

**Comment by ntfstool** [comment]
The latest version V2.3.0 has been updated, and you can experience whether the problem is solved.If it is still not resolved, please contact the official technical service.

**Comment by zqxu8888** [comment]
macos10.15.6，ntfstool2.3.2， windows系统盘 自动挂载，然后马上被卸载，再重新挂载，循环好多次才停止。如何禁止自动挂在某个盘？

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
