### ISSUE TITLE
无限挂载和移除，MacBook Pro 自带键盘和触摸板

### ISSUE THREAD

**Issue by Vie-Any** [ntfstool/ntfstool#15]
系统：OS X 10.15.4
NTFSTools：V2.2.0
型号MacBook Pro 16 inch
合上盖子处于休眠状态时，会频繁的通知移除和挂载本子自带的键盘和触摸板
<img width="341" alt="QQ20200507-084944@2x" src="https://user-images.githubusercontent.com/6085618/81242465-c4f5bd80-903f-11ea-9174-171e80f5ed8a.png">

**Comment by phuud** [comment]
Meet the same issue...
macOS 10.14.6
NTFSTools 2.2.0 
It was OK in 2.1.x

**Comment by ntfstool** [comment]
The latest version V2.3.0 has been updated, (the external USB notification can be specifically disabled), if it is still not resolved, please contact the official technical service.

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
