### ISSUE TITLE
Javascript error dialog

### ISSUE THREAD

**Issue by curdaneta** [ntfstool/ntfstool#17]
Hello

I got an error dialog on mac OS 10.15.4 using version 2.3.0 on a MacBook Pro (15-inch, 2016) 16 GB ram, 256 Flash storage.

> A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> ReferenceError: dialog is not defined
>     at /Applications/NTFSTool.app/Contents/Resources/app.asar/dist/electron/main.js:1:5550
>     at IncomingMessage.returnString (/Applications/NTFSTool.app/Contents/Resources/app.asar/node_modules/get/lib/index.js:261:13)
>     at IncomingMessage.emit (events.js:215:7)
>     at endReadableNT (_stream_readable.js:1183:12)
>     at processTicksAndRejections (internal/process/task_queues.js:80:21)

Best regards
Ciro

**Comment by curdaneta** [comment]
Another JS error

> Uncaught Exception:
> ReferenceError: dialog is not defined
>     at /Applications/NTFSTool.app/Contents/Resources/app.asar/dist/electron/main.js:1:5550
>     at IncomingMessage.returnString (/Applications/NTFSTool.app/Contents/Resources/app.asar/node_modules/get/lib/index.js:261:13)
>     at IncomingMessage.emit (events.js:210:5)
>     at TLSSocket.socketCloseListener (_http_client.js:372:11)
>     at TLSSocket.emit (events.js:215:7)
>     at net.js:658:12
>     at TCP.done (_tls_wrap.js:481:7)

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
