### ISSUE TITLE
Tray icon not center-vertically aligned

### ISSUE THREAD

**Issue by irpray** [ntfstool/ntfstool#18]
NTFSTool for Mac version 2.3.2
MacOS Catalina 10.15.4

Tray icon is not well-aligned like any other apps. It would be nice if it's center-vertically aligned.
Thank you :)

![Screen Shot 2020-05-14 at 13 18 112](https://user-images.githubusercontent.com/11201738/81900585-4ec8fc00-95e7-11ea-848c-301a5115c738.png)

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
