### ISSUE TITLE
读写速度很慢

### ISSUE THREAD

**Issue by jdjingdian** [ntfstool/ntfstool#19]
机械硬盘正常读写大概100M/s的样子，用mac原生命令行的方式挂载基本也能跑到跟在windows下一样的性能水平，但是用ntfstools挂载之后读写只有20M左右，这正常吗？

**Comment by sur-lee** [comment]
的确是的，昨天下载试用，速度20M/S不到的样子。

**Comment by zwb124** [comment]
目前还不支持usb3.0传输，所以还需要继续改进

**Comment by jdjingdian** [comment]
> 目前还不支持usb3.0传输，所以还需要继续改进

我是用雷电转sata的，我看这个软件需要安装fuse，所以想可不可能是因为底层用ntfs-3g造成的性能低

**Comment by zwb124** [comment]
> > 目前还不支持usb3.0传输，所以还需要继续改进
> 
> 我是用雷电转sata的，我看这个软件需要安装fuse，所以想可不可能是因为底层用ntfs-3g造成的性能低

可是Tuxera NTFS底层好像也是ntfs-3g，可能人家做了改进优化吧，所以这个还需要更多人参与改进，我目前还是在用mounty，只要不拷贝单个文件，就没啥问题，还支持高速传输，如果这个软件也支持高速传输了，我就准备换了

**Comment by NanerLee** [comment]
确实慢, 我用这个挂载之后向挂载的硬盘写入只有 10MB/s 作用

**Comment by dr1llc4t** [comment]
> 没

mounty有缺陷，经常会因为attr文件造成文件不可编辑。mounty使用需要有一定的动手能力。

**Comment by zwb124** [comment]
告诉你个方法，只要你拷贝的是文件夹，就没事，如果必须拷贝单个文件就先把文件放到文件夹里复制过去，然后再在移动硬盘里把文件拷贝出来，文件夹删除就ok了

发自我的iPhone

**Comment by dr1llc4t** [comment]
> 告诉你个方法，只要你拷贝的是文件夹，就没事，如果必须拷贝单个文件就先把文件放到文件夹里复制过去，然后再在移动硬盘里把文件拷贝出来，文件夹删除就ok了 发自我的iPhone
> […](#)
> 在 2020年6月11日，17:01，dr1llc4t ***@***.***> 写道： ﻿ 没 mounty有缺陷，经常会因为attr文件造成文件不可编辑。mounty使用需要有一定的动手能力。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

就怕哪天一不小心忘了......然后就得一顿terminal操作

**Comment by zwb124** [comment]
如果你经常用移动硬盘，还是建议你买个正版，Tuxera ntfs优惠后不到100块，也不贵的

**Comment by Johnova** [comment]
> 目前还不支持usb3.0传输，所以还需要继续改进

作者意识到这个问题？估计啥时候能修复

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
