### ISSUE TITLE
Electron随系统启动隐藏主窗口

### ISSUE THREAD

**Issue by tenndou** [ntfstool/ntfstool#20]
大佬你好，首先试用了一下ntfstool，目前感觉的问题主要就是速度问题，其他感觉很好，希望尽快迭代。
另外麻烦问个困扰很久的问题，我发现ntfstool跟随系统启动的时候可以只显示菜单栏图标而不显示主窗口，且docker图标也不会显示。想请问如何做到的，我开发的程序随系统启动后虽然窗口可以隐藏，但docker的图标还是会闪一下再消失。
望大佬不吝赐教，感谢！

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
