### ISSUE TITLE
先显示只读，过几秒之后就是未挂载状态

### ISSUE THREAD

**Issue by lnaf** [ntfstool/ntfstool#21]
ntfstool版本：2.3.2、mac os版本：10.15.5
无论是先插入硬盘再启动APP，还是先启动APP再插入硬盘，都无法挂载。都是先显示只读，过几秒之后就是未挂载状态。

**Comment by xsxnet** [comment]
the same

> ntfstool版本：2.3.2、mac os版本：10.15.5
> 无论是先插入硬盘再启动APP，还是先启动APP再插入硬盘，都无法挂载。都是先显示只读，过几秒之后就是未挂载状态。

**Comment by snow212-cn** [comment]
同楼主！无法使用ntfstool，已卸

**Comment by FinallyFinancialFreedom** [comment]
+1 根本无法使用.

**Comment by lackneets** [comment]
<img width="903" alt="截圖 2020-09-12 下午10 45 00" src="https://user-images.githubusercontent.com/3694058/92997986-c41eec00-f549-11ea-9b05-7ba80bc8df97.png">

根本沒作用啊？也找不到如何掛載

**Comment by fxdm41202425** [comment]
同样的问题，请问怎么解决？

**Comment by lankecheng** [comment]
+1

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
