### ISSUE TITLE
U盘不识别？

### ISSUE THREAD

**Issue by rochy2014** [ntfstool/ntfstool#22]
插入一个NTFS格式的U盘，只有提示，确没有识别到

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
