### ISSUE TITLE
10.15.5 (19F101)  Unsupported macOS Version

### ISSUE THREAD

**Issue by angurs92** [ntfstool/ntfstool#23]
The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.

**Comment by shuiche-it** [comment]
遇到里同样的问题

**Comment by dengly** [comment]
遇到里同样的问题

**Comment by shuiche-it** [comment]
> 遇到里同样的问题

我这里破解了一个Paragon NTFS for Mac15. 由于个人经济原因, 就没有买正版, 如果您需要,可以联系我. 当然优先推荐您支持正版软件

**Comment by k928116312** [comment]
> > 遇到里同样的问题
> 
> 我这里破解了一个 Paragon NTFS for Mac15 版本。由于个人经济原因，就不用买正版，如果您需要，可以联系我。优先推荐您支持正版软件

请问支持m1芯片，可否一次安装一直使用

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
