### ISSUE TITLE
为什么会一直挂载

### ISSUE THREAD

**Issue by myxss** [ntfstool/ntfstool#24]
![image](https://user-images.githubusercontent.com/33475775/85944634-ec477780-b96a-11ea-9249-bb71509da1e4.png)

**Comment by myxss** [comment]
mac os 10.15

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
