### ISSUE TITLE
System Error 10050

### ISSUE THREAD

**Issue by MingqianYang** [ntfstool/ntfstool#25]
这是什么意思？一个劲的跳出这个。我还以为这个软件是个流氓软件呢！！

<img width="360" alt="Screen Shot 2020-07-08 at 12 18 17 pm" src="https://user-images.githubusercontent.com/15353430/86866991-5acbc880-c115-11ea-8797-6329e21c1c70.png">

**Comment by zhaQinweikun** [comment]
我得也是,重新安装也不行 系统是15.5,

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
