### ISSUE TITLE
2.3.2 的安装过程要求输入电脑密码

### ISSUE THREAD

**Issue by Navimark** [ntfstool/ntfstool#26]
**非常感谢作者的开源工具！**
问题描述：2.3.2 版本下载时在 Github Release 中没有原始链接了，被导向一个看起来是分发破解软件的网站。当 2.3.2 下载完成后，双击打开时明显能感受到安装包被第三方套壳处理过，出现了第三方的品牌名，而且要求输入密码，不知道是 App 合法的提权请求还是第三方擅自添加的提权请求，让人不放心。希望能在 Github Release 页面添加原始 .dmg 下载链接，或者原始代码压缩包方便自行 Release
![WX20200708-150501](https://user-images.githubusercontent.com/4392747/86888913-88247080-c12d-11ea-8bf8-868cd47e6482.png)
![截屏2020-07-08 下午3 05 16](https://user-images.githubusercontent.com/4392747/86888922-89ee3400-c12d-11ea-835c-cc065e15e00c.png)

**Comment by jiangbeisheng** [comment]
1. macwk.com这是个宝藏网站，希望你能明鉴
2. 不放心的话可以brew cask install ntfstool

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
