### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by FriedrichTschen** [ntfstool/ntfstool#28]
What a great App for Macs! But here are some issues which could be improved.
First, when i connect a NTFS device to mac, it takes usually  several times of tries of mount before a stable connection established.
And, when this App activates, the Temperature of the cup on my mac is seriously high, which is hotter then normal states about 10 Celciusgrade.
Without those problems above, this app is still a great job for every user of macOS, thanks a lot.

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
