### ISSUE TITLE
读写速度很慢

### ISSUE THREAD

**Issue by niceczj** [ntfstool/ntfstool#30]
- 版本: 2.3.2
- 系统: macOS 10.15.6 (19G73)
- USB: 3.0
复制速度只有11Mb/s，而Paragon 的有120MB/s

**Comment by revaraver** [comment]
的确很慢,我还以为是mac的锅,换了软件后才知道了是软件的问题

**Comment by youkongling** [comment]
> 的确很慢,我还以为是mac的锅,换了软件后才知道了是软件的问题

二楼的老哥有什么软件可以推荐下吗？

**Comment by revaraver** [comment]
> > 的确很慢,我还以为是mac的锅,换了软件后才知道了是软件的问题
> 
> 二楼的老哥有什么软件可以推荐下吗？

目前在试用Tuxera NTFS,速度能到70MB/s左右,虽然不到我的硬盘的正常速度(180MB/s),但好歹能凑活用了

**Comment by niceczj** [comment]
> > > 的确很慢,我还以为是mac的锅,换了软件后才知道了是软件的问题
> > 
> > 
> > 二楼的老哥有什么软件可以推荐下吗？
> 
> 目前在试用Tuxera NTFS,速度能到70MB/s左右,虽然不到我的硬盘的正常速度(180MB/s),但好歹能凑活用了

老铁，是买的正版吗，不是共享下？

**Comment by Johnova** [comment]
这速度确实很慢，有没有啥解决办法？
我看mounty也可以，但经常remount出错。。
fuse安装太费劲了，需要mac进recovery模式修改mount_ntfs

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
