### ISSUE TITLE
Internal Memory Card Reader

### ISSUE THREAD

**Issue by dtapps** [ntfstool/ntfstool#33]
为什么偶尔会一直提示这个？也没发现这个硬盘
![image](https://user-images.githubusercontent.com/16093106/91534409-1229d200-e944-11ea-9dcc-08275c151e6f.png)

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
