### ISSUE TITLE
访达边栏中快捷方式的问题

### ISSUE THREAD

**Issue by mcyaas** [ntfstool/ntfstool#34]
开发者，您好！
首先非常感谢开发NTFSTOOL，非常方便。
下面，说一下我在使用中遇到的问题。
PC主机中安装了双系统，机械硬盘的NTFS分区共享资料使得在Mac 和win 都能使用。
每次电脑重启，Mac访达的边栏中，快捷方式文件夹就会消失。
给文件夹分配的标签颜色也会消失。
这在以前使用其他ntfs软件（Tuxera NTFS/Mounty for NTFS）中是没有问题的。
麻烦修复/增加此项功能。谢谢！
![iShot2020-09-09 19 22 13](https://user-images.githubusercontent.com/70827507/92592190-cb3bc500-f2d1-11ea-944f-139ac18ab20e.jpg)

系统：Mac os 10.15.3 (19D76)
版本：2.3.2 (3245)
硬盘接口:SATA

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
