### ISSUE TITLE
挂载以后只能只读

### ISSUE THREAD

**Issue by skysinger** [ntfstool/ntfstool#35]
挂在NTFS移动硬盘以后，磁盘状态是只读

**Comment by zhangyubushiyu** [comment]
同样遇到这个问题。

**Comment by yoczhang** [comment]
The same problem.

**Comment by dweigit** [comment]
the same problem

**Comment by kedup** [comment]
I meet this problem too

**Comment by wweiradio** [comment]
I met this problem .

![image](https://user-images.githubusercontent.com/3864595/99774319-9c02c900-2b48-11eb-8478-12569331d270.png)

The disk mounted as readonlye.

**Comment by baaaaatu** [comment]
内置ntfs硬盘挂在后无法写

**Comment by shunichio** [comment]
同样遇到这个问题。

**Comment by amourz** [comment]
ntfs 只能读不能写，big sur系统

**Comment by howeroc** [comment]
big sur 11.1 the same problem

**Comment by FeedHedgehog** [comment]
I meet this same problem too ,The ntfs disk mounted as readonly.

**Comment by c517718004** [comment]
ntfs 只能读不能写，majove系统

**Comment by kedup** [comment]
no one know why?

**Comment by PaddyPang** [comment]
the same problem

**Comment by snowlee946** [comment]
same problem

**Comment by song52wow** [comment]
same problem

**Comment by Tsyshiu** [comment]
> ntfs 只能读不能写，majove系统

same

**Comment by JackKuo-tw** [comment]
same problem

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
