### ISSUE TITLE
从系统状态栏点击进入偏好设置时打开的是反馈界面

### ISSUE THREAD

**Issue by newforesee** [ntfstool/ntfstool#36]
![image](https://user-images.githubusercontent.com/40905664/93417243-2412eb00-f8da-11ea-8422-0e80ca361571.png)
版本 2.3.2 (3245)
从系统状态栏点击进入偏好设置时打开的是反馈界面
![image](https://user-images.githubusercontent.com/40905664/93417290-4dcc1200-f8da-11ea-8d53-7ad00d238319.png)

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
