### ISSUE TITLE
Uses all system memory available until macos no longer can work

### ISSUE THREAD

**Issue by metinn** [ntfstool/ntfstool#37]
After reboot, nftstool used so much memory, macos asked me to close some apps. 
i managed to open activity monitor to see it uses 15.3gb of ram

ntfstool: 2.3.0
macos catalina: 10.15.6

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
