### ISSUE TITLE
希捷移动硬盘没法挂载

### ISSUE THREAD

**Issue by zhangyubushiyu** [ntfstool/ntfstool#38]
提示如下
Unsupported macOS Version
The installed version of FUSE is too old for the operating system. Please upgrade your FUSE installation to one that is compatible with the currently running version of macOS.

**Comment by XuCpeng** [comment]
1. 能不能挂载与硬盘品牌无关
2. 提示已经说得很清楚了，系统不兼容

所以如果你真的想解决问题，应该首先贴出你的系统环境，出现问题的过程，而不只是扔上这样一段话，这样别也没有办法帮你。

**Comment by ixsim** [comment]
希捷的硬盘去希捷官网下载官方工具就可以了。

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
