### ISSUE TITLE
System password with ' symbol

### ISSUE THREAD

**Issue by gab-** [ntfstool/ntfstool#39]
I have the alert message "Password cannot contain symbols ' ".
Yes, but my password contains a ' symbol.

**Comment by fenglinzeng** [comment]
me too.and later i change my password.lol

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
