### ISSUE TITLE
挂载节点名称混乱 磁盘使用信息错误

### ISSUE THREAD

**Issue by Z-fly** [ntfstool/ntfstool#42]
![image](https://user-images.githubusercontent.com/10470892/99490200-5ad1b400-29a4-11eb-87f0-bcce0244ad34.png)

![image](https://user-images.githubusercontent.com/10470892/99490430-c61b8600-29a4-11eb-8d3d-db38cb2adceb.png)

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
