### ISSUE TITLE
现在版本不支持MacOS Big Sur吗？

### ISSUE THREAD

**Issue by mypopcs** [ntfstool/ntfstool#43]
插上移动硬盘不会自动mount，只能只读。什么时候发布新版本呀

**Comment by ldlywt** [comment]
MARK,更新了麻烦说声

**Comment by bingtianbaihua** [comment]
+1

**Comment by weijinsun** [comment]
看起来  好像不维护了的样子

**Comment by dadaFive** [comment]
+1

**Comment by sweetweapen** [comment]
+1

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
