### ISSUE TITLE
It seems not support the new OS

### ISSUE THREAD

**Issue by Chester-li** [ntfstool/ntfstool#44]
After the hard disk is mounted , it can only read but not write.  
OS: Big Sur

**Comment by Aiman26864** [comment]
After installation, the program does not work for me either, you can only read

**Comment by lemenyalex** [comment]
Same

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
