### ISSUE TITLE
该磁盘未挂载

### ISSUE THREAD

**Issue by wangtian076** [ntfstool/ntfstool#45]
![image](https://user-images.githubusercontent.com/9692429/102003165-c0645680-3d3e-11eb-9747-8bf18f5ae87e.png)

**Comment by Optimus-Prime-X** [comment]
![image](https://user-images.githubusercontent.com/34361559/102842510-11143780-4442-11eb-83b5-379a1149015e.png)

The same error (sad)

**Comment by gitlyp** [comment]
me too

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
