### ISSUE TITLE
Change font for the interface

### ISSUE THREAD

**Issue by jukrb0x** [ntfstool/ntfstool#46]
suppose a font like Myriad would make all things look better ;)

**Comment by jukrb0x** [comment]
Actually, it's fine but the preview screenshot looks bad.

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.

**Comment by jukrb0x** [comment]
thanks a lot!
