### ISSUE TITLE
Any chance to use the native password verification?

### ISSUE THREAD

**Issue by sneko** [ntfstool/ntfstool#48]
Hi,

When trying to unmount my disk I get this window:
![image](https://user-images.githubusercontent.com/8195958/103239726-be111780-494e-11eb-8cd6-20b56ec78f80.png)

It looks really homemade and didn't make me feel confident about entering my system password into it. For sure I could check all the code source to see my password is not sent somewhere else... but I'm wondering if @ntfstool you could find a way to instead use the native MacOS password prompt?

Thank you,

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
