### ISSUE TITLE
笔记本睡眠后启动总是弹出窗口

### ISSUE THREAD

**Issue by RuoBingCoder** [ntfstool/ntfstool#50]
弹出窗口很烦，明明挂载着，又弹出好几个反馈的窗口！

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
