### ISSUE TITLE
uninstall

### ISSUE THREAD

**Issue by hzwjs** [ntfstool/ntfstool#52]
how to uninstall

**Comment by hzwjs** [comment]
卸载ntfs后出现的
<img width="761" alt="image" src="https://user-images.githubusercontent.com/8175184/105571807-0aa11480-5d8e-11eb-8480-2aecb0c38536.png">

**Comment by pmardav** [comment]
restart, quit and uninstall

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.

**Comment by Allan-Mo** [comment]
After click install button in the GUI for an external disk, it change the file system personality to "ntfstool". But i cannot mount the disk. So i uninstall it by delete from Applications. And now I cannot mount it by any other software like Mounty or Paragon or mont command, because of the changed file system personality is "ntfstool". How can i restore the file system type personality back to "UFSD_NTFS", which is "Microsoft NTFS"?

`sudo diskutil listFileSystems`
-------------------------------------------------------------------------------
PERSONALITY                     USER VISIBLE NAME                               
-------------------------------------------------------------------------------
UFSD_NTFS                       Microsoft NTFS                                  
ntfstool                        Windows NTFS by ntfstool Software  

`sudo diskutil info -all`

**********
   Device Identifier:         disk2s1
   Device Node:               /dev/disk2s1
   Whole:                     No
   Part of Whole:             disk2

   Volume Name:               Meimei
   Mounted:                   No

   Partition Type:            Windows_NTFS
   File System Personality:   ntfstool
   Type (Bundle):             ntfstool
   Name (User Visible):       Windows NTFS by ntfstool Software
