### ISSUE TITLE
big sur用户日常催更

### ISSUE THREAD

**Issue by Allen148** [ntfstool/ntfstool#53]
big sur用户日常催更，大佬求求你更新下吧

**Comment by jaxwang** [comment]
big sur用户日常催更

**Comment by kfcceo** [comment]
big sur都催更。。更不用说M1了

**Comment by czzonet** [comment]
卧槽 原来不能用 早说啊
我有空看看能不能提个pr修复一下

**Comment by zhuohualuo** [comment]
M1 催更

**Comment by xihrni** [comment]
big sur+m1 催更

**Comment by simosun** [comment]
日常崔一下

**Comment by Leungmax** [comment]
m1 日常崔一下

**Comment by ivaquero** [comment]
m1 日常崔一下

**Comment by crane168** [comment]
big sur 日常催更

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
