### ISSUE TITLE
跟本不能用

### ISSUE THREAD

**Issue by codebanking** [ntfstool/ntfstool#54]
没有任何操作功能，就是为了看一个磁盘列表吗？求解，这个软件是怎么用的？只是显示一个磁盘列表吗？

**Comment by goudan-learner** [comment]
...这个软件就是在mac中，可以向ntfs格式的硬盘里写入文件，还要操作什么？

**Comment by tqzone** [comment]
but 你说的功能并不存在……

**Comment by goudan-learner** [comment]
不存在什么鬼，你安装后不能向ntfs硬 盘里写入文件吗

**Comment by goudan-learner** [comment]
还是你升级到了bigsur

**Comment by tqzone** [comment]
我记得是没有任何改变。文件写入也不行。和之前是一样的，也没有升级。

**Comment by tqzone** [comment]
稍等，再试一遍。

**Comment by tqzone** [comment]
我是catalina 10.15.7

**Comment by tqzone** [comment]
看到这个熟悉的界面，我一下就想起来了。列表里现实的除了未挂载，剩下的都显示只读。

**Comment by goudan-learner** [comment]
## 还不能用吗

**Comment by tqzone** [comment]
显示的界面，除了未挂载，就是只读。是的，不能用的。所以我很费解。没有任何操作。只能看见当前磁盘的列表以及状态。

**Comment by tqzone** [comment]
原来如此，我还以为有神秘的操作功能。使之可以变成读写。但是我发现没有任何操作功能。所以才很费解。

**Comment by lankecheng** [comment]
确实是不能用呀

- 系统信息

![system](https://wx3.sinaimg.cn/mw690/6b365e91gy1goijeycp55j20wk0jmacl.jpg)

- 失败信息

![fail](https://wx1.sinaimg.cn/mw690/6b365e91ly1goij97dwsbj219f0u0dj7.jpg)

**Comment by tqzone** [comment]
自己写个shell脚本挂载吧

**Comment by xihrni** [comment]
我也是，最新系统，Macmini，还费劲装上了要求插件，重启了2次就只能看个列表

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
