### ISSUE TITLE
10.15.7上无法使用

### ISSUE THREAD

**Issue by zhangyue2030** [ntfstool/ntfstool#56]
你好！NTFS TOOl for MAC之前非常好用，然后系统更新到10.15.7突然就挂载不上NTFS固态硬盘了，更新了macFUSE也没用

**Comment by jiangzm** [comment]
mounty 支持最新系统

**Comment by Hareis** [comment]
是的 我也是只读

**Comment by IMsuperM** [comment]
我也是只读，能解决嘛

**Comment by bolosea** [comment]
the same to you

**Comment by DukeDeng** [comment]
Monterey 只读。

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
