### ISSUE TITLE
Try to mount NTFS drives manually on 10.15.7  automatically unmount after seconds

### ISSUE THREAD

**Issue by realkris** [ntfstool/ntfstool#57]
我在macOS Catalina 10.15.7和tool 2.3.5上遇到了这个问题，并多次复现：步骤如下
I encountered the issue on macOS Catalina and ntfstool 2.3.5 and you can follow these sequences below which are repeatable:

1. Mac插入移动硬盘、U盘（USB 3.0，使用紫米拓展坞，工作正常），安装NTFSTOOL，之后硬盘被弹出了。NTFStool显示未装载。我手动装载了硬盘，显示只读，几秒后再次被自动弹出，NTFStool显示未装载，无法访问此硬盘。如此反复
Insert and mount(system automatically) the flashdisk and MHD using ZMI typeC dock, while at this moment the devices work fine and read only. Install ntfstool after that, and the disks(flashdisk and MHD) were unmounted(also automatically ), while the tool's preface showing that the disks are unmounted. I tried to mount the disks manually using macOS's Disk Utility, same time the tool's preface showed the disks are read only, however just seconds, the disks were unmounted(auto.) again.

2. 之后我卸载了NTFS Tool，使用App Cleaner。系统正常装载了硬盘，没有自动弹出，正常使用（当然，不可写）。
I uninstalled ntfstool by then using App Cleaner and my Mac now could mount the drives normally, without auto-ejections or unmount(not writable, of course).

有人可以回答如何解决吗，十分感谢？
Is there someone helps me out this issue?
thanks alot

**Comment by realkris** [comment]
btw, Paragon NTFS works fine, maybe it is not system issue? I just tested by trail.

**Comment by wxl356** [comment]
I have the same issue, cannot mount the disk on macOS Catalina 10.15.7 and tool 2.3.2

**Comment by PengXing** [comment]
I have the same issue, even the latest version v2.3.2.

NTFSTool unmouts the disk, I just mounted on by the commnd `diskutil mountDisk /dev/disk2`

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
