### ISSUE TITLE
Energy Consumption Too High

### ISSUE THREAD

**Issue by dukexmnc** [ntfstool/ntfstool#59]
I installed NTSFTool yesterday but when I turned my MacBook Pro Mid-2015 this morning the fans were running hard and it turned out to be caused by NTSFTool app, which was the #1 energy user on the Activity Monitor.

I disable NTSFTool from the LogIn Items and the fans are not creating lot noise any more.  My MBP specs are listed below.

  macOS Big Sur 11.5.2 (20G95)
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,5
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.5 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	427.140.8.0.0

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
