### ISSUE TITLE
Just a question on how to use ntfstool

### ISSUE THREAD

**Issue by takobaba** [ntfstool/ntfstool#61]
I have installed the tool on big sur, how do I mount or unmount NTFS disks? There is only unmount after its automatically mounted and my disk is not mounted as read/write enabled. I also couldn't find any information on the repo, how to.

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
