### ISSUE TITLE
m1+Monterey上面好像用不了

### ISSUE THREAD

**Issue by lethal233** [ntfstool/ntfstool#63]
我按照文档安装了fuse和ntfstool，看到ntfs硬盘挂载了，但是还是可读的，写不进去
是没有适配还是什么原因？

**Comment by hitzhangjie** [comment]
It warns the FUSE is not compatible with current Mac.

CPU: m1 chip
OS: macOS monterey

**Comment by lethal233** [comment]
> It warns the FUSE is not compatible with current Mac.
> 
> CPU: m1 chip OS: macOS monterey

okay, i did not notice that when i installed the FUSE in my computer. I just clicked and rebooted the computer. thx very much.

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
