### ISSUE TITLE
每次关屏和开屏后都会自动弹出主界面。

### ISSUE THREAD

**Issue by cklx0719** [ntfstool/ntfstool#64]
我每次盖上屏幕，然后再打开屏幕时，软件都会自动弹出了主界面，以及设置界面和反馈界面。

![image](https://user-images.githubusercontent.com/25605487/145550452-0bd9b965-f48e-4eea-b51e-3539d3d51925.png)

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
