### ISSUE TITLE
看来马可波罗m1 白嫖太难了啊

### ISSUE THREAD

**Issue by tengyz** [ntfstool/ntfstool#65]
看来马可波罗m1 白嫖太难了啊 好久没有更新了

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
