### ISSUE TITLE
我使用Monterey intel core i5不能够写入

### ISSUE THREAD

**Issue by luokunman** [ntfstool/ntfstool#67]
我查阅了很多资料，并且还是不能够成功使用写入功能。能否同意通过qq群讨论。
<img width="593" alt="image" src="https://user-images.githubusercontent.com/41885648/171141840-4f651504-cbd2-4def-9bd2-049a11d9b313.png">

**Comment by luokunman** [comment]
找到原因 执行node_modules/ntfstool/ntfs-tool 可执行程序时，报 ntfstool inner need update

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
