### ISSUE TITLE
18款MacBookPro最新系统不能写入呀

### ISSUE THREAD

**Issue by ZhongChunle** [ntfstool/ntfstool#69]
只能读取数据不能写出

**Comment by happy-func** [comment]
MacBook Pro
16-inch, 2019
+1

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
