### ISSUE TITLE
Fuse及软件下载成功，但是硬盘依然无法进行读写操作

### ISSUE THREAD

**Issue by helen-hjy** [ntfstool/ntfstool#72]
一开始fuse的版本说不支持macos13，我上官网下载了4.4.1版本的是ok的，但是通过ntfs tools打开硬盘依然无法删除文件操作。

**Comment by coder-free** [comment]
一样的问题，ntfs硬盘无法写入
mac 系统版本  12.6.2 (21G320)
fuse 版本  4.4.1
ntfstool 版本 2.3.2

**Comment by wyfang** [comment]
same

**Comment by Facemax** [comment]
same

**Comment by Tomosawa** [comment]
一样的问题，都装了还是没用。
macOS 13.0 M2芯片
fuse 4.4.2
ntfstool 2.3.2
打开ntfstool也没有任何的提示，插入NTFS盘后，总之就是和啥也没装一个效果。

**Comment by MadMaxChow** [comment]
我也是这个情况，不知道怎么操作，也没有什么指引

**Comment by dengzhe-hou** [comment]
same

**Comment by muta6086** [comment]
是这样的

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
