### ISSUE TITLE
三年过去了，我写了个脚本可以支持，大佬有时间的话，可否更新了一下了。

### ISSUE THREAD

**Issue by hoochanlon** [ntfstool/ntfstool#73]
大佬不嫌代码简陋的话，可以参考我写的脚本，看看能不能整合一下。毕竟图形化才能更好普及呀。

https://github.com/hoochanlon/Free-NTFS-for-Mac/blob/main/nigate.sh

在线试用

```
/bin/bash -c "$(curl -fsSL https://cdn.statically.io/gh/hoochanlon/Free-NTFS-for-Mac/main/nigate.sh)"
```

前提：homebrew、网速好、SIP关闭、终端完全权限，
推荐：开发者、IT人士、Mac老鸟

**Comment by wangmeijian** [comment]
执行这个命令就行？

**Comment by hoochanlon** [comment]
有说明，你自己去看 README 和 FAQ ：

* https://github.com/hoochanlon/Free-NTFS-for-Mac/blob/main/README.md
* https://github.com/hoochanlon/Free-NTFS-for-Mac/issues/9
* https://github.com/hoochanlon/Free-NTFS-for-Mac/issues/3

> 执行这个命令就行？

**Comment by ntfstool** [comment]
Thanks you!!!
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.
