### ISSUE TITLE
MacBookPro M1 最新系统不能写入

### ISSUE THREAD

**Issue by qx1956** [ntfstool/ntfstool#75]
只能读取数据不能写出

**Comment by qx1956** [comment]
MacBook Pro
13-inch, M1 2020 macOS Sonoma 14.1

**Comment by XinyeWu007** [comment]
> MacBook Pro
> 13-inch, M1 2020 macOS Sonoma 14.1

My MacBook Pro, M1 Pro, Ventura 13.6 can't write as well.

**Comment by huyuanjun976** [comment]
MacBook Air M1 也不行

**Comment by ntfstool** [comment]
The new version 3.5+ already supports Apple M1/M2/M3 and other chips.

Sorry for taking so long to update, because before that there was no good way to solve the compatibility problem of the new version of the system.

Fortunately, we have now been authorized by Apple to support the new version of the system kernel, so that we can fully support all macos systems through kernel drivers. Please experience it again, and if you have any questions, please update and communicate.

**Comment by BYNepenthe** [comment]
M3 还是不行
版本用的是 3.5.1
