### ISSUE TITLE
一直重复装载卸载

### ISSUE THREAD

**Issue by LittlBear** [ntfstool/ntfstool#8]
您好！重启后，出现分区重复一直装载→卸载→再装载→再卸载...

**Comment by ntfstool** [comment]
Okay, we will check this issue, thanks for the feedback

**Comment by ntfstool** [comment]
This updated version has solved this problem, please download and view
https://github.com/ntfstool/ntfstool/releases/tag/2.2.0

**Comment by LittlBear** [comment]
2.2.0,The problem still exists.

**Comment by ntfstool** [comment]
ok, you can contact the QQ group to see the solution on the official website (https://ntfstool.com/zh-cn/index.html)

**Comment by ntfstool** [comment]
The reason is: due to the rapid shutdown of windows10, cache caching, forced loading will damage the data, so linux directly denied access.

The solutions are:-Re-enter windows and shut down normally. Just enter centos. However, this problem occurs again every time Windows quickly shuts down-restart into Windows, and turn off the Quick Start function in Control Panel-Power Options

As of NTFSTool2.2.0, there is no function to repair the cache forcibly mounting, you can try the above methods to solve it.

**Comment by LittlBear** [comment]
The problem has been solved, thanks!
